import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header />
      <main>
        <h1>Welcome to My Project</h1>
        <p>This is the home page.</p>
      </main>
      <Footer /> */}
    </>
  );
};

export default Home;
