'use client'
import { ReactNode } from 'react';
import { ThemeProvider } from 'styled-components';
import GlobalStyle from '../styles/GlobalStyles';
import theme from '../styles/theme';
import Footer from '../components/Footer';
import styled from 'styled-components';
import React from 'react';
import Head from 'next/head';
const Body = styled.body`
  display: flex;
  min-height: 100vh;
  flex-direction: column;
  justify-content: flex-start;
  position:relative;
`
const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <ThemeProvider theme={theme}>
          <GlobalStyle />
          {children}
          <Footer />
        </ThemeProvider>
      </Body>
    </html>
  );
};

export default RootLayout;
